### ISSUE TITLE
Installation instructions/docker?

### ISSUE THREAD

**Issue by philipdistefano** [Ryan10145/year-in-pixels-creator#3]
Hey there, this looks really cool!  I tried installing it with the current instructions without much luck (installs and comes up on port 3000 and 5000, but the app gives an error about secrets that I don't quite understand - text of the error pasted below).  Any chance you're planning a docker container or can provide more insight on what I may be doing wrong?  Thank you!
```

Error: secret option required for sessions
    at session (/home/philip/year-in-pixels-creator/node_modules/express-session/index.js:200:12)
    at Layer.handle [as handle_request] (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:317:13)
    at /home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:335:12)
    at next (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/philip/year-in-pixels-creator/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:317:13)
    at /home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:335:12)
    at next (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/philip/year-in-pixels-creator/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:317:13)
    at /home/philip/year-in-pixels-creator/node_modules/express/lib/router/index.js:284:7
```

**Comment by rcya1** [comment]
Hi, thanks for checking out the project! Sorry that the description for setting up the project aren't the best. The main thing is that the project expects a .env file to exist in the root directory with the following parameters:

ATLAS_URI=<REDACTED>
PORT=5000
SESSION_SECRET=<REDACTED>
VERIFICATION_EMAIL=<REDACTED>
VERIFICATION_PASSWORD=<REDACTED>

These include private security information such as passwords / API links. So if you want to try running the program locally, you'll have to create a MongoDB Atlas project and pass in the URI here, create a randoms string for the session secret (this can be literally anything afaik), and then the credentials for a gmail account for verification emails.

If you already defined the SESSION_SECRET variable and are still having issues, then let me know! Unfortunately I'm not the most experienced with Docker and also I'm not entirely sure if it would help in this situation because the issue seems to be more of just defining the correct environment variables to get the code running.

**Comment by philipdistefano** [comment]
Thanks for the response and for putting this project out there! 

So, I do have the .env file with the session_secret and the Mongo database (and the other items as well).  I am not super familiar with Mongo though.  Is there a particular format for passing the MongoDB in the .env file?

**Comment by rcya1** [comment]
Hi, you should be able to get this link from the MongoDB Atlas website when you go to the page for the cluster you created. After you click connect, you should be able to find a string that looks something along the lines of this:

mongodb+srv://<REDACTED>:<REDACTED>cluster0.<REDACTED>

As a bit of a guide, I used this tutorial: https://medium.com/@beaucarnes/learn-the-mern-stack-by-building-an-exercise-tracker-mern-tutorial-59c13c1237a1 to help me set up this project. It's been a while since I first set it up so the interface might have changed, but the core ideas should be the same.

**Comment by philipdistefano** [comment]
🤦‍♂️ I am just realizing that MongoDB Atlas is specifically the online MongoDB rather than the self-hosted one.  Does this project support self-hosted MongoDB?

edit:  I tried MongoDB Atlas and no dice; same error.

Here is what I see on my server after I issue 'npm start' in the root directory:


```
> year-in-pixels-server@1.0.0 start /home/philip/year-in-pixels-creator
> node index.js

express-session deprecated req.secret; provide secret option index.js:20:17
Server is listening on port: 5000
(node:1974) UnhandledPromiseRejectionWarning: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefi                                       ned". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/home/philip/year-in-pixels-creator/node_modules/mongoose/lib/connection.js:694:1                                       1)
    at _mongoose._promiseOrCallback.cb (/home/philip/year-in-pixels-creator/node_modules/mongoose/lib/index.js:351:10)
    at Promise (/home/philip/year-in-pixels-creator/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/philip/year-in-pixels-creator/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/home/philip/year-in-pixels-creator/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/home/philip/year-in-pixels-creator/node_modules/mongoose/lib/index.js:350:20)
    at Object.<anonymous> (/home/philip/year-in-pixels-creator/index.js:64:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:1974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of                                        an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that                                        are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by rcya1** [comment]
Hi, currently there isn't support for self-hosted Mongo databases. That error is strange because it looks like it wasn't able to properly read the URI from the .env file. The way the project works is that inside of the index.js file, the `process.env.ATLAS_URI` looks at the .env file and reads in what ATLAS_URI is set to. If possible, can you send a picture of what your root directory of the project looks like to see if the .env file is put in the correct place? It should be on the same level of the index.js, /app, /modules, etc.

**Comment by philipdistefano** [comment]
Absolutely!  

![YIPC](https://user-images.githubusercontent.com/103964399/164836847-24a689c5-6563-4a99-8992-50fbc21d3b95.PNG)

Here's my .env file too in case that helps (with redactions, of course):

![YIPCenv](https://user-images.githubusercontent.com/103964399/164837744-14723288-58d1-47d5-bc6a-21014663ca09.PNG)


I appreciate you taking time to troubleshoot this. :)

**Comment by rcya1** [comment]
Oh, I think I see the issue here. The format of the .env file should be VARIABLE_NAME=VARIABLE_VALUE instead of VARIABLE_NAME: VARIABLE_VALUE. Additionally, you shouldn't need quotes (for instance the port line should be PORT=5000)

**Comment by philipdistefano** [comment]
🤦‍♂️ Thank you so much for your help and for creating/sharing this awesome project!  It works! :)  Even seems to work with my locally installed MongoDB!

**Comment by rcya1** [comment]
Awesome, and glad to hear it!
